### PR TITLE
Update carpentries_workshops.tsv

### PR DESCRIPTION
**Pull request by javibio-git**
Updated instructor names for Carnegie Institution and Practical Genomics

### CODE REVIEW

**Comment by mblue9** [comment]
Thanks @javibio-git !

**Comment by javibio-git** [comment]
@mblue9 Just noticing that my changes are not reflected on `devel`. Was there maybe an error? Or Did I miss something?

Thank you!

**Comment by mblue9** [comment]
Thanks for catching that. Was nothing you did, I had to force push to fix an unrelated issue and it overwrote your changes. I've added and they should be live in a couple minutes.

**Comment by javibio-git** [comment]
Thank you @mblue9!

**Pull request merged**
